### ISSUE TITLE
Select dinamico (Categoria,Papel,Tamaño,Borde,Cantidad)

### ISSUE THREAD

**Issue by Machi3mfl** [Machi3mfl/laboratorio#1]
En Crear nuevo pedido, crear SELECT dinámico de opciones. 

en /pedidos/add

**Comment by joniborda** [comment]
Necesito un poco mas de info.
¿Queres hacer que en el select se puede agregar otras opciones? porque se muestran las opciones.
o en otro lado vas hacer un amb de estas opciones?

**Comment by joniborda** [comment]
Armar una tabla que sea papel_tamanos y categoria_papels para hacer los filtros de estos selectores.

**Comment by joniborda** [comment]
Lista, al seleccionar la categoria se cargan los tipos de papeles y al seleccioanr los papeles se cargan los tamaños.
